version: '3'

services:
  client:
    build:
      context: .
      dockerfile: config/Dockerfile.production
    ports:
      - "80:80"
    container_name: weather_production
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules