version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: weather
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules