version: '3'

services:
  client:
    build:
      context: .
      dockerfile: config/Dockerfile.develop
    ports:
      - "3000:3000"
    container_name: weather_develop
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules