FROM node:alpine AS builder

WORKDIR /app

COPY . .

RUN yarn install && yarn react-scripts build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/build .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]